apiVersion: apps/v1
kind: Deployment
metadata: 
  name: admin-depl
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: admin
  template: 
    metadata: 
      labels: 
        app: admin
    spec: 
      containers: 
        - name: admin
          image: abinv/admin
          env:
            - name: MONGO_URI
              value: 'mongodb://admin-mongo-srv:27017/admin'
            - name: MONGO_URL_ADMIN
              valueFrom: 
                secretKeyRef:
                  name: devhive-mongo-url-admindbdevhive
                  key: MONGO_URL_ADMINDB_DEVHIVE
            - name: JWT_SECRET_KEY
              valueFrom: 
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET_KEY
            - name: JWT_REFRESH_SECRET_KEY
              valueFrom: 
                secretKeyRef:
                  name: jwt-refresh-secret
                  key: JWT_REFRESH_SECRET_KEY
---
apiVersion: v1
kind: Service
metadata: 
  name: admin-srv
spec: 
  selector: 
    app: admin
  ports: 
    - name: admin
      protocol: TCP
      port: 3000
      targetPort: 3000