apiVersion: apps/v1
kind: Deployment
metadata: 
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: auth
  template: 
    metadata: 
      labels: 
        app: auth
    spec: 
      containers: 
        - name: auth
          image: abinv/auth
          env:
            - name: MONGO_URI
              value: 'mongodb://auth-mongo-srv:27017/auth'
            - name: MONGO_URL_AUTH
              valueFrom: 
                secretKeyRef:
                  name: devhive-mongo-url-auth
                  key: MONGO_URL_AUTHDB_DEVHIVE
            - name: JWT_SECRET_KEY
              valueFrom: 
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET_KEY
            - name: JWT_REFRESH_SECRET_KEY
              valueFrom: 
                secretKeyRef:
                  name: jwt-refresh-secret
                  key: JWT_REFRESH_SECRET_KEY
            - name: TWILIO_AUTH_TOKEN
              valueFrom: 
                secretKeyRef:
                  name: twilio-auth-token
                  key: TWILIO_AUTH_TOKEN
            - name: TWILIO_ACCOUNT_SID
              valueFrom: 
                secretKeyRef:
                  name: twilio-account-sid
                  key: TWILIO_ACCOUNT_SID
            - name: TWILIO_SERVICE_SID
              valueFrom: 
                secretKeyRef:
                  name: twilio-service-sid
                  key: TWILIO_SERVICE_SID
---
apiVersion: v1
kind: Service
metadata: 
  name: auth-srv
spec: 
  selector: 
    app: auth
  ports: 
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000