apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-depl
spec:
  selector:
    matchLabels:
      app: zookeeper
  replicas: 2
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: bitnami/zookeeper
        ports:
        - containerPort: 2181
        env:
        - name: ALLOW_ANONYMOUS_LOGIN
          value: "yes"
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
---

apiVersion: v1
kind: Service
metadata:
  name: zookeeper-srv
spec:
  selector:
    app: zookeeper
  ports:
  - name: client
    protocol: TCP
    port: 2181
    targetPort: 2181